# Generated by Django 4.2.4 on 2023-10-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_item_category_alter_item_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Футболки та Топи'), ('SW', 'Спортивні костюми'), ('SW', 'Сорочки'), ('OW', 'Худі'), ('OW', 'Шорти'), ('OW', 'Куртки'), ('OW', 'Кросівки'), ('OW', 'Сандалі'), ('OW', 'Чоботи'), ('OW', 'Шкарпетки')], max_length=2, verbose_name='Категорія'),
        ),
    ]
