# Generated by Django 4.2.4 on 2023-10-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('JN', 'Джинси'), ('JK', 'Куртки'), ('SN', 'Кросівки'), ('SA', 'Сандалі'), ('S', 'Сорочки'), ('SW', 'Спортивні костюми'), ('TT', 'Футболки та топи'), ('HS', 'Худі та толстовки'), ('BT', 'Чоботи'), ('P', 'Штани'), ('SH', 'Шорти'), ('SC', 'Шкарпетки')], max_length=2, verbose_name='Категорія'),
        ),
    ]
