# Generated by Django 4.2.4 on 2023-11-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('WI', 'Зима'), ('SP', 'Весна'), ('SU', 'Літо'), ('AU', 'Осінь')], max_length=5, verbose_name='Мітка'),
        ),
    ]
