# Generated by Django 4.2.4 on 2023-11-05 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_item_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
    ]
