from django.urls import path
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    HomeHeaderView,
    AboutHeaderView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    createProduct,
    accessories_category,
    baseball_caps_category,
    jackets_category,
    caps_category,
    sneakers_category,
    pajamas_category,
    sandals_category,
    shirts_category,
    tracksuits_category,
    t_shirts_and_tops_category,
    hoodies_and_sweatshirts_category,
    boots_category,
    pants_and_jeans_category,
    shorts_category,
    socks_category,
    search,
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('/', HomeHeaderView.as_view(), name='home'),
    path('about/', AboutHeaderView.as_view(), name='about'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('create_product.html/', createProduct, name='create-product'),
    path('accessories_category/', accessories_category, name='accessories_category'),
    path('baseball_caps_category/', baseball_caps_category, name='baseball_caps_category'),
    path('jackets_category/', jackets_category, name='jackets_category'),
    path('caps_category/', caps_category, name='caps_category'),
    path('sneakers_category/', sneakers_category, name='sneakers_category'),
    path('pajamas_category/', pajamas_category, name='pajamas_category'),
    path('sandals_category/', sandals_category, name='sandals_category'),
    path('shirts_category/', shirts_category, name='shirts_category'),
    path('tracksuits_category/', tracksuits_category, name='tracksuits_category'),
    path('t-shirts_and_tops_category/', t_shirts_and_tops_category, name='t-shirts_and_tops_category'),
    path('hoodies_and_sweatshirts_category/', hoodies_and_sweatshirts_category, name='hoodies_and_sweatshirts_category'),
    path('boots_category/', boots_category, name='boots_category'),
    path('pants_and_jeans_category/', pants_and_jeans_category, name='pants_and_jeans_category'),
    path('shorts_category/', shorts_category, name='shorts_category'),
    path('socks_category/', socks_category, name='socks_category'),
    path('search/', search, name='search'),
]
